sudo: required

language: node_js

services: docker

before_install:
  - docker-compose up --build -d

script:
  - docker-compose ps
  - docker-compose exec frontend yarn test
  - docker-compose exec backend yarn test
