sudo: required

language: node_js

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.8.0

before_install:
  - docker-compose up --build -d

script:
  - cd backend && cat Dockerfile
  - cd frontend && cat Dockerfile
  - docker-compose ps
  - docker-compose logs
  - docker-compose exec frontend yarn test
  - docker-compose exec backend yarn test
