sudo: required

language: node_js
node_js:
  - lts/*

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.8.0

before_install:
  - docker-compose up --build -d
  - cd frontend && yarn install
  - ls

script:
  - docker-compose ps
  - docker-compose logs
