sudo: required

language: node_js

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - npx create-react-app --typesctipt
  - yarn add express node-dev
  - docker-compose up --build -d

script:
  - docker-compose ps
  - docker-compose logs
  - docker-compose exec frontend_1 yarn test
  - docker-compose exec backend_1 yarn test
