sudo: required

language: node_js
node_js:
  - lts/*

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.8.0

before_install:
  - docker-compose up --build -d
  - cd frontend && yarn install
  - cd .. && cd backend && yarn install

script:
  - docker-compose ps
  - docker-compose logs
  - docker-compose exec frontend yarn test
  - docker-compose exec backend yarn test
