sudo: required

language: node_js
node_js:
  - lts/*

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.8.0

before_install:
  - docker-compose up --build -d
  - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com
  - cd frontend && yarn install --frozon-lockfile && ls
  - cd .. && cd backend && yarn install --frozon-lockfile && ls
  - cd ~ && ls

script:
  - docker-compose up -d
  - docker-compose exec frontend yarn test --watchAll=false
  - docker-compose exec backend yarn test --watchAll=false

deploy:
  provider: script
  script:
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f frontend/Dockerfile.prod .;
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f backend/Dockerfile.prod .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app $HEROKU_APP_NAME;
  on:
    branch: master
