version: 2.1
#あとで修正
orbs:
  welcome: circleci/welcome-orb@0.4.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - dockerhub-creds

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: docker-app:frontend
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
      - image: docker-app:backend
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          command: 'docker-compose up --build -d'
      - run:
          command: 'docker-compose up -d'
